"""initial_cartier_schema

Revision ID: 646c50a61eea
Revises: 
Create Date: 2026-05-20 09:09:18.544821+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646c50a61eea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('jobs_queue_index'))

    op.drop_table('jobs')
    op.drop_table('migrations')
    op.drop_table('system_user')
    op.drop_table('cloud_config')
    op.drop_table('cloud_task_detail')
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cache_expiration_index'))

    op.drop_table('cache')
    op.drop_table('cloud_conversation')
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('failed_jobs_connection_queue_failed_at_index'))
        batch_op.drop_index(batch_op.f('failed_jobs_uuid_unique'))

    op.drop_table('failed_jobs')
    op.drop_table('cloud_user_project')
    op.drop_table('cloud_customer')
    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sessions_last_activity_index'))
        batch_op.drop_index(batch_op.f('sessions_user_id_index'))

    op.drop_table('sessions')
    with op.batch_alter_table('cache_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cache_locks_expiration_index'))

    op.drop_table('cache_locks')
    op.drop_table('job_batches')
    op.drop_table('users')
    op.drop_table('cloud_message')
    op.drop_table('cloud_task')
    op.drop_table('cloud_quick_reply')
    with op.batch_alter_table('cloud_phoneinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('idfa')

    with op.batch_alter_table('cloud_project', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('cloud_received_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tcard_conversation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tcard_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key(None, 'tcard_conversation', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tcard_task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tcard_task_detail', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key(None, 'tcard_task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tcard_task_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('tcard_task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('tcard_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('tcard_conversation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cloud_received_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cloud_project', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cloud_phoneinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idfa', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('cloud_quick_reply',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_task',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('task_name', sa.VARCHAR(), nullable=False),
    sa.Column('project_key', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('fail_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_message',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('from_id', sa.INTEGER(), nullable=True),
    sa.Column('to_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('msg_type', sa.VARCHAR(), server_default=sa.text('("text")'), nullable=True),
    sa.Column('direction', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('is_read', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_risk', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_blacklist', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('send_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(), nullable=True),
    sa.Column('user_type', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('login_ip', sa.VARCHAR(), nullable=True),
    sa.Column('login_time', sa.DATETIME(), nullable=True),
    sa.Column('backend_setting', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job_batches',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('total_jobs', sa.INTEGER(), nullable=False),
    sa.Column('pending_jobs', sa.INTEGER(), nullable=False),
    sa.Column('failed_jobs', sa.INTEGER(), nullable=False),
    sa.Column('failed_job_ids', sa.TEXT(), nullable=False),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('cancelled_at', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('finished_at', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cache_locks',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('owner', sa.VARCHAR(), nullable=False),
    sa.Column('expiration', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('cache_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('cache_locks_expiration_index'), ['expiration'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('last_activity', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sessions_user_id_index'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('sessions_last_activity_index'), ['last_activity'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('cloud_customer',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('system_phonenumber', sa.VARCHAR(), nullable=True),
    sa.Column('project_key', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_user_project',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('phoneinfo_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('message_available', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failed_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(), nullable=False),
    sa.Column('connection', sa.VARCHAR(), nullable=False),
    sa.Column('queue', sa.VARCHAR(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('exception', sa.TEXT(), nullable=False),
    sa.Column('failed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('failed_jobs_uuid_unique'), ['uuid'], unique=1)
        batch_op.create_index(batch_op.f('failed_jobs_connection_queue_failed_at_index'), ['connection', 'queue', 'failed_at'], unique=False)

    op.create_table('cloud_conversation',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('phoneinfo_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('unread_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_favorite', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_message', sa.TEXT(), nullable=True),
    sa.Column('last_message_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cache',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('expiration', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('cache_expiration_index'), ['expiration'], unique=False)

    op.create_table('cloud_task_detail',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('phoneinfo_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('send_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_config',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('config_key', sa.VARCHAR(), nullable=False),
    sa.Column('config_value', sa.TEXT(), nullable=True),
    sa.Column('remark', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('system_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(), nullable=True),
    sa.Column('user_type', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('login_ip', sa.VARCHAR(), nullable=True),
    sa.Column('login_time', sa.DATETIME(), nullable=True),
    sa.Column('backend_setting', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('migration', sa.VARCHAR(), nullable=False),
    sa.Column('batch', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('queue', sa.VARCHAR(), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('reserved_at', sa.INTEGER(), nullable=True),
    sa.Column('available_at', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('jobs_queue_index'), ['queue'], unique=False)

    # ### end Alembic commands ###
